### ISSUE TITLE
Install Error :'(

### ISSUE THREAD

**Issue by programmerpsk** [peterbraden/node-opencv#577]
This is my installation step in window.

**1**. Download and install OpenCV
**2**. If you haven't already, create a system variable called OPENCV_DIR and set it to C:\OpenCV\build\x64\vc12
Make sure the "x64" part matches the version of NodeJS you are using.
Also add the following to your system PATH ;%OPENCV_DIR%\bin
**3**. npm install --global --production windows-build-tools
**4**. then npm i opencv

but it occurs error.. (below)

(this is part of error text in cmd)

===================================================================

c:\opencv\build\include\opencv2\flann\dist.h : warning C4819: The file contains a character that cannot be represented
in the current code page (949). Save the file in Unicode format to prevent data loss (compiling source file ..\src\LDAW
rap.cc) [C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
c:\opencv\build\include\opencv2\flann\dist.h : warning C4819: The file contains a character that cannot be represented
in the current code page (949). Save the file in Unicode format to prevent data loss (compiling source file ..\src\Hist
ogram.cc) [C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(25): error C2131: expression did not evaluate to a constant [C:\Users\Park Seongkuk\Desktop\salient
-image-master\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Histogram.cc(25): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\src\Histogram.cc(25): note: see usage of 'dims'
..\src\Histogram.cc(26): error C2131: expression did not evaluate to a constant [C:\Users\Park Seongkuk\Desktop\salient
-image-master\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Histogram.cc(25): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\src\Histogram.cc(25): note: see usage of 'dims'
..\src\Histogram.cc(28): error C3863: array type 'int [dims]' is not assignable [C:\Users\Park Seongkuk\Desktop\salient
-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(33): error C2131: expression did not evaluate to a constant [C:\Users\Park Seongkuk\Desktop\salient
-image-master\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Histogram.cc(25): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\src\Histogram.cc(25): note: see usage of 'dims'
..\src\Histogram.cc(35): error C3863: array type 'int [dims]' is not assignable [C:\Users\Park Seongkuk\Desktop\salient
-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(41): error C2131: expression did not evaluate to a constant [C:\Users\Park Seongkuk\Desktop\salient
-image-master\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Histogram.cc(25): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\src\Histogram.cc(25): note: see usage of 'dims'
..\src\Histogram.cc(42): error C2131: expression did not evaluate to a constant [C:\Users\Park Seongkuk\Desktop\salient
-image-master\node_modules\opencv\build\opencv.vcxproj]
  ..\src\Histogram.cc(25): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\src\Histogram.cc(25): note: see usage of 'dims'
..\src\Histogram.cc(48): error C3863: array type 'float [dims][2]' is not assignable [C:\Users\Park Seongkuk\Desktop\sa
lient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(49): error C3863: array type 'float [dims][2]' is not assignable [C:\Users\Park Seongkuk\Desktop\sa
lient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(50): error C3863: array type 'const float *[dims]' is not assignable [C:\Users\Park Seongkuk\Deskto
p\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(68): warning C4311: 'type cast': pointer truncation from 'int *' to 'unsigned int' [C:\Users\Park S
eongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(68): warning C4302: 'type cast': truncation from 'int *' to 'unsigned int' [C:\Users\Park Seongkuk\
Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(73): warning C4311: 'type cast': pointer truncation from 'int *' to 'unsigned int' [C:\Users\Park S
eongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(73): warning C4302: 'type cast': truncation from 'int *' to 'unsigned int' [C:\Users\Park Seongkuk\
Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(78): warning C4311: 'type cast': pointer truncation from 'int *' to 'unsigned int' [C:\Users\Park S
eongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
..\src\Histogram.cc(78): warning C4302: 'type cast': truncation from 'int *' to 'unsigned int' [C:\Users\Park Seongkuk\
Desktop\salient-image-master\node_modules\opencv\build\opencv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\Park Seongkuk\\Desktop\\salient-image-master\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v48-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\Users\\Park Seongkuk\\Desktop\\salient-image-master\\node_modules\\opencv\\build\\opencv\\v6.0.0\\Release\\node-v48-win32-x64"
gyp ERR! cwd C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Park Seongkuk\\Desktop\\salient-image-master\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64\opencv.node --module_name=opencv --module_path=C:\Users\Park Seongkuk\Desktop\salient-image-master\node_modules\opencv\build\opencv\v6.0.0\Release\node-v48-win32-x64' (1)
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "opencv"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! opencv@6.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@6.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs opencv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Park Seongkuk\Desktop\salient-image-master\npm-debug.log

===================================================================

I found many answers in google.
but nobody told me the exact solution.

how can I fix this ERROR ???

**Comment by btsimonh** [comment]
historgram should be fixed now in master.
please try again and report?

**Comment by programmerpsk** [comment]
wow success! thank you!
but It still occur errors in other directory(not master directory) when I type 'npm install' in cmd.
can you update bug fixed version?

**Comment by btsimonh** [comment]
I note that salient-image is referencing in it's package.json git+https://github.com/piercus/node-opencv.git - i.e. not this repo.  You'll need to check that his repo does not have something special to make salient-image work :). (looks like it's ok).

Until peter updates the NPM repo with the master branch, you can install the master branch directly using:

npm install peterbraden/node-opencv#master

and you *could* modify your salient-image package.json to have:
  "dependencies": {
    "opencv": "peterbraden/node-opencv#master"
  }

then they should install as one.

reference the test; if I run that command, it passes Matrix toBuffer, but fails at MatchTemplateByMatrix
I'm using an OpenCV 3.3.1 pre-build with a vc14 build directory...
I didn't get test failures on travis for my latest PRs, so we can probably assume it does not fail in linux.
Although I'm not sure of if this test is run, or if it just runs all examples...

**Comment by programmerpsk** [comment]
I solve errors based on your comment.
Thank you so much! ^^
